model:
  base_learning_rate: 5.0e-6
  target: ldm.models.diffusion.ddpm_pseudo3D.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: volume_data
    cond_stage_key: ref_and_volume_seg
    cond_stage_trainable: false
    conditioning_key: concat
    image_size: 64
    channels: 4
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    ckpt_path: path-to-stage1-ckpt
    load_only_unet: True
    fix_t: True

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel_pseudo3D.UNetModel
      params:
        image_size: 64
        in_channels: 12
        out_channels: 4
        model_channels: 224
        attention_resolutions: [ 8, 4, 2 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 3, 4 ]
        num_head_channels: 32
        use_spatial_transformer: false
        transformer_depth: 1
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        ckpt_path: 'models/first_stage_models/kl-f8/model.ckpt'
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_first_stage__

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 5
    wrap: false
    train:
      target: ldm.data.volume_dataset.volume_train
      params:
        data_root: './data/nnUNet_preprocessed/'
        data_name: 'Dataset202_Brain'
        data_repeat: 100
    validation:
      target: ldm.data.volume_dataset.volume_val
      params:
        data_root: './data/nnUNet_preprocessed/'
        data_name: 'Dataset202_Brain'


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 20000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True